### PR TITLE
Properly skip source and javadoc generation.

### PR DESCRIPTION
**Pull request by aressem**
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Review by arnej27959 — COMMENTED** [review]
you should probably change "-DskipTests" to "-Dmaven.test.skip=true" also?

**Review by geirst — APPROVED** [review]
👍

**Comment by aressem** [comment]
@arnej27959 Depend if we would like the tests to compile. `maven.test.skip=true` will skip compile+run of tests, while `skipTests` will compile the tests without running them. The `skipJavadoc` was part of an profile activation that I intend to remove.

**Review by arnej27959 — APPROVED** [review]
as long as you know what you want to happen, this sounds good!

**Pull request merged**
